language: php

php:
 - "7.1"
 - "7.3"

env:
  matrix:
  - PREFER_LOWEST=""
  - PREFER_LOWEST="--prefer-lowest"

before_script:
 - composer update --no-interaction $PREFER_LOWEST

script:
 - vendor/bin/phpunit
 - composer phpstan

after_script:
 - php vendor/bin/coveralls -v
